### ISSUE TITLE
Cant execute KadeHub with JJSploit

### ISSUE THREAD

**Issue by CantStopTheA-Train** [skibiditoiletfan2007/KadeHubRepository#2]
for some reason i cant execute kade hub and when im pressing execute nothing happens and on second time theres a window "kade hub already executed" and theres no hub gui (also i cant execute any other public scripts)

**Comment by skibiditoiletfan2007** [comment]
Is this a joke? JJsploit is just shit

**Comment by CantStopTheA-Train** [comment]
> Is this a joke? JJsploit is just shit

even tho zorara and jjsplot has same unc (77%) and solara v3 has 66% and i can execute kade hub with solara now

**Comment by CantStopTheA-Train** [comment]
> > Is this a joke? JJsploit is just shit
> 
> even tho zorara and jjsplot has same unc (77%) and solara v3 has 66% and i can execute kade hub with solara now

nvm now its working on all 3
